<?php
    $keyboard = array(
        'toprow' => array(
            'q'                => array('key' => 'q', 'class' => 'blue'),
            'w'                => array('key' => 'w', 'class' => 'blue'),
            'e'                => array('key' => 'e', 'class' => 'blue'),
            'r'                => array('key' => 'r', 'class' => 'blue'),
            't'                => array('key' => 't', 'class' => 'green'),
            'y'                => array('key' => 'y', 'class' => 'green'),
            'u'                => array('key' => 'u', 'class' => 'green'),
            'i'                => array('key' => 'i', 'class' => 'green'),
            'o'                => array('key' => 'o', 'class' => 'red'),
            'p'                => array('key' => 'p', 'class' => 'red'),
            'l-square-bracket' => array('key' => '[', 'class' => 'red'),
            'r-square-bracket' => array('key' => ']', 'class' => 'yellow'),
        ),
        'middlerow' => array(
            'a'          => array('key' => 'a',  'class' => 'blue'),
            's'          => array('key' => 's',  'class' => 'blue'),
            'd'          => array('key' => 'd',  'class' => 'blue'),
            'f'          => array('key' => 'f',  'class' => 'blue'),
            'g'          => array('key' => 'g',  'class' => 'green'),
            'h'          => array('key' => 'h',  'class' => 'green'),
            'j'          => array('key' => 'j',  'class' => 'green'),
            'k'          => array('key' => 'k',  'class' => 'red'),
            'l'          => array('key' => 'l',  'class' => 'red'),
            'semicolon'  => array('key' => ';',  'class' => 'red'),
            'apostrophe' => array('key' => '\'', 'class' => 'yellow'),
        ),
        'bottomrow' => array(
            'z'             => array('key' => 'z', 'class' => 'blue'),
            'x'             => array('key' => 'x', 'class' => 'blue'),
            'c'             => array('key' => 'c', 'class' => 'blue'),
            'v'             => array('key' => 'v', 'class' => 'blue'),
            'b'             => array('key' => 'b', 'class' => 'green'),
            'n'             => array('key' => 'n', 'class' => 'green'),
            'm'             => array('key' => 'm', 'class' => 'red'),
            'comma'         => array('key' => ',', 'class' => 'red'),
            'period'        => array('key' => '.', 'class' => 'red'),
            'forward-slash' => array('key' => '/', 'class' => 'yellow'),
        ),
    );
